### PR TITLE
Added a Travis CI Badge in ReadMe

### LINKED ISSUE #2: Add Travis CI badge in readme

### PR DESCRIPTION
**Pull request by Michaellin250**
Fixes #2 

I ran the project in Travis CI and got the badge and placed it into the ReadMe. I forked the project, cloned it, ran Travis, and then I pasted the build status of the badge into the ReadMe. I didn't know how else to do it. If i did something wrong please let me know.

### CODE REVIEW

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Correct URL is https://travis-ci.org/tapaswenipathak/KAPIs.svg?branch=master.

**Comment by Michaellin250** [comment]
I fixed it!

**Comment by Michaellin250** [comment]
Is there still a problem?

**Comment by tapaswenipathak** [comment]
Squash the commits.

**Comment by tapaswenipathak** [comment]
Pl. squash the commits.

**Comment by tapaswenipathak** [comment]
Looks good, pl. squash the commits.

**Comment by Michaellin250** [comment]
What do I do now?

**Comment by tapaswenipathak** [comment]
Oh I added few commits, you can

- `git pull origin master` or `git merge master` in your branch
- `git rebase -i gitsha` (gitsha - value should be just the previous till the gitsha you are squashing)
- This should open a interactive rebase. There you can squash the commits in one commit.
- After rebase, you can update the pull request.

Have a read of what is squashing in git. You will find information online.

**Comment by Michaellin250** [comment]
I squashed the commits! Is the issue now closed? Or do I still need to make changes?

**Comment by tapaswenipathak** [comment]
This is great work! :) Did you `git merge master` or `git pull origin master`? You can see git conflicts in this pr, these are as I added few commits from the time you created this pr. Do you want to run the command as well and fix this? Let me know otherwise I will do it.

**Comment by tapaswenipathak** [comment]
I merged your work from cmd. Looks great, when rebasing you should have dropped the extra commit, I merged from cmd.

**Comment by tapaswenipathak** [comment]
I merged your work. Looks great, while rebasing you should have dropped the extra commit, I merged using command line.

**Comment by tapaswenipathak** [comment]
I merged your work.

**Comment by tapaswenipathak** [comment]
I merged using command line.

**Pull request closed without merging**
